export const listOfProdacts = [
  {
    id: '1',
    title: 'Rice semolina Garnets glute',
    category: 'Cereals',
    calories: '340',
    weight: '100',
    recommended: true,
  },
  {
    id: '2',
    title: 'Venison stew Special',
    category: 'Meat',
    calories: '81',
    weight: '100',
    recommended: false,
  },
  {
    id: '3',
    title: 'Bread Hercules grain',
    category: 'Flour',
    calories: '289',
    weight: '100',
    recommended: true,
  },
  {
    id: '4',
    title: 'Banana juice',
    category: 'Soft drinks',
    calories: '48',
    weight: '100',
    recommended: false,
  },
  {
    id: '5',
    title: 'Spikachki',
    category: 'Sausage',
    calories: '337',
    weight: '100',
    recommended: false,
  },
  {
    id: '6',
    title: 'Coffee drink',
    category: 'Soft Drinks',
    calories: '337',
    weight: '100',
    recommended: false,
  },
  {
    id: '7',
    title: 'Red onion',
    category: 'Vegetables and herbs',
    calories: '42',
    weight: '100',
    recommended: false,
  },
  {
    id: '8',
    title: 'Homemade noodles',
    category: 'Flour',
    calories: '332',
    weight: '100',
    recommended: true,
  },
];
