export const dashboardData = [
  {
    icon: '../../../../public/img/sprait.svg#calorie-intake',
    title: 'Daily calorie intake',
    count: 2200,
    countType: 'cal',
    background: 'accent',
    textColor: 'whiteTextColor',
  },
  {
    icon: '../../../../public/img/sprait.svg#physical-activity',
    title: 'Daily physical activity',
    count: 110,
    countType: 'time',
    background: 'accent',
    textColor: 'whiteTextColor',
  },
  {
    icon: '../../../../public/img/sprait.svg#calories-consumed',
    title: 'Сalories consumed',
    count: 707,
    countType: 'cal',
    background: 'default',
    textColor: 'greyTextColor',
  },
  {
    icon: '../../../../public/img/sprait.svg#calories-burned',
    title: 'Сalories burned',
    count: 855,
    countType: 'cal',
    background: 'default',
    textColor: 'greyTextColor',
  },
  {
    icon: '../../../../public/img/sprait.svg#calories-remaining',
    title: 'Calories remaining',
    count: -100,
    countType: 'cal',
    background: 'default',
    textColor: 'greyTextColor',
  },
  {
    icon: '../../../../public/img/sprait.svg#sports-remaining',
    title: 'Sports remaining',
    count: 85,
    countType: 'time',
    background: 'default',
    textColor: 'greyTextColor',
  },
];
